program: lstm_rainfall8.py
method: random
metric:
  name: val_accuracy
  goal: maximize

parameters:
  batch_size:
    values: [32, 64, 128, 256]

  learning_rate:
    distribution: log_uniform
    min: -7.6
    max: -6.2

  lstm_units1:
    values: [64, 128]

  lstm_units2:
    values: [32, 64]

  dropout1:
    values: [0.2, 0.3, 0.4]

  dropout2:
    values: [0.2, 0.3, 0.4]

  l2_reg:
    values: [0.0001, 0.00005]

  threshold:
    distribution: uniform
    min: 0.3
    max: 0.5

